### ISSUE TITLE
[Feature Request] A flag for tree-like output

### ISSUE THREAD

**Issue by rashil2000** [gardebring/PowerColorLS#6]
The `tree.com` Windows command is extremely old and very limited. It'd be nice to have a flag for showing tree-like output, something like [jit-tree](https://github.com/rabadiw/ps1/tree/master/jit-tree) does.

**Comment by gardebring** [comment]
That would indeed be nice. Sorry to say I am lacking in time right now so I will not have the time to look into this in the short term. If anyone want's to provide a PR I am more than happy to include it and I might do it myself eventually when I have the time otherwise. I will close this for now.
