### ISSUE TITLE
Possibility to use without the need for nerd fonts (i.e. disable icons)

### ISSUE THREAD

**Issue by musm** [gardebring/PowerColorLS#9]
Hello,

I like the colorized output, but don't have a nerd font or don't necessarily want to create my own patched font. As a result, I was wondering if there was an option to disable the terminal icons and still use your package?
Thanks

**Comment by gardebring** [comment]
Hi. Sorry for late reply. There was an option to do this but it seems it has stopped working. I will try and find some time to look into this.

**Comment by gardebring** [comment]
Hi @musm . This is available with the _-hi_ or _--hide-icons_ option.
You can see information about this by doing `PowerColorLS --help` or simply type in `PowerColorLS -hi`
I will close this issue. Please comment or reopen if you have any further issues.

**Comment by musm** [comment]
Thanks!

**Comment by gardebring** [comment]
You are welcome :)
